name: Run Bruno API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bruno-collections:
    runs-on: ubuntu-latest

    env:
      BRUNO_PATH: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.1'

      - name: Install Bruno CLI
        id: install-bruno
        run: |
          npm install @usebruno/cli
          echo "BRUNO_PATH=$(pwd)/node_modules/.bin/bru" >> $GITHUB_ENV
          echo "Bruno installed at: $(pwd)/node_modules/.bin/bru"
          ls -l $(pwd)/node_modules/.bin
          $(pwd)/node_modules/.bin/bru --version || echo "Bru executable not found!"

      - name: Run Collection FakestoreAPI
        working-directory: ${{ github.workspace }}/FakestoreAPI
        run: ${{ env.BRUNO_PATH }} run --env QA .
