name: Run Bruno API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bruno-collections:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.1'

      - name: Install Bruno CLI
        id: install-bruno
        run: |
          npm install @usebruno/cli
          echo "BRUNO_PATH=$(pwd)/node_modules/.bin/bruno" >> $GITHUB_ENV
        working-directory: ${{ github.workspace }}

      - name: Debug Directory
        run: pwd && ls -R

      - name: Run Collection DemoAurelienClimaginaire
        working-directory: ${{ github.workspace }}/DemoAurelienClimaginaire
        run: $BRUNO_PATH run --env environments/Prod_Climaginaire.bru .

      - name: Run Collection FakestoreAPI
        working-directory: ${{ github.workspace }}/FakestoreAPI
        run: $BRUNO_PATH run --env environments/QA.bru .

      - name: Run Collection Webinar_Climaginaire
        working-directory: ${{ github.workspace }}/Webinar_Climaginaire
        run: $BRUNO_PATH run --env environments/Webinar_Prod_Climaginaire.bru .
