name: Run Bruno API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bruno-collections:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Bruno CLI
        run: |
          npm install -g @usebruno/cli
          # Ajouter le chemin des binaires npm globaux au PATH
          export PATH=$(npm config get prefix)/bin:$PATH
          echo "Bruno installed at: $(npm config get prefix)/bin"
          echo "PATH updated to: $PATH"
          bruno --version

      - name: Debug Directory
        run: pwd && ls -R

      - name: Run Collection DemoAurelienClimaginaire
        working-directory: DemoAurelienClimaginaire
        run: bruno run --env environments/Prod_Climaginaire.bru .

      - name: Run Collection FakestoreAPI
        working-directory: FakestoreAPI
        run: bruno run --env environments/QA.bru .

      - name: Run Collection Webinar_Climaginaire
        working-directory: Webinar_Climaginaire
        run: bruno run --env environments/Webinar_Prod_Climaginaire.bru .
