name: Run Bruno API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bruno-collections:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.1'

      - name: Install Bruno CLI
        run: npm install @usebruno/cli

      - name: Debug Directory
        run: pwd && ls -R

      - name: Run Collection DemoAurelienClimaginaire
        working-directory: DemoAurelienClimaginaire
        run: ../node_modules/.bin/bruno run --env environments/Prod_Climaginaire.bru .

      - name: Run Collection FakestoreAPI
        working-directory: FakestoreAPI
        run: ../node_modules/.bin/bruno run --env environments/QA.bru .

      - name: Run Collection Webinar_Climaginaire
        working-directory: Webinar_Climaginaire
        run: ../node_modules/.bin/bruno run --env environments/Webinar_Prod_Climaginaire.bru .
